<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8c0d3bb0-7c5a-43b3-93af-9fac00705b6d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.2.0" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="ModelContextProtocol" Version="0.3.0-preview.4" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.3.0-preview.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />

    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />

    <PackageReference Include="Microsoft.Identity.Client" Version="4.79.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientLibrary\ClientLibrary.csproj" />
  </ItemGroup>

</Project>
